05_LargeFlaskApp/project/models.py
# models.py
# Setup 'db' inside __init__.py under project directory
from project import db

class Child(db.Model):
    __tablename__ = 'child'

    id = db.Column(db.Integer, primary_key=True)
    cname = db.Column(db.Text)
    father = db.relationship('Father', backref='child', uselist=False) # One - One : uselist must be False

    def __init__(self,cname):
        self.cname = cname

    def __repr__(self):
        if self.father:
            return f"ID: {self.id} Child: {self.cname} Father: {self.father.fname}"
        else:
            return f"ID: {self.id} Child: {self.cname} Father: NULL"

class Father(db.Model):
    __tablename__ = 'father'

    id = db.Column(db.Integer, primary_key=True)
    fname = db.Column(db.Text)
    child_id = db.Column(db.Integer, db.ForeignKey('child.id'))

    def __init__(self,fname,child_id):
        self.fname = fname
        self.child_id = child_id

05_LargeFlaskApp/project/child/forms.py
#forms.py - child
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of the Child:')
    submit = SubmitField('Enroll Child')

class DelForm(FlaskForm):
    id = IntegerField('Child ID to Remove:')
    submit = SubmitField('Remove Child')

05_LargeFlaskApp/project/father/forms.py
#forms.py - father
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField

class AddForm(FlaskForm):
    name = StringField('Name of the Father:')
    child_id = IntegerField("ID of the Child:")
    submit = SubmitField('Adopt Child')

05_LargeFlaskApp/project/__init__.py
# __init__.py under project dir

import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

basedir = os.path.abspath(os.path.dirname(__file__))

app.config['SECRET_KEY'] = 'rizwan'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.db')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

db = SQLAlchemy(app)
migrate = Migrate(app,db)

# blueprints are registered after db is defined

from project.child.views import child_blueprint
from project.father.views import father_blueprint

app.register_blueprint(father_blueprint, url_prefix='/father')
app.register_blueprint(child_blueprint, url_prefix='/child')

05_LargeFlaskApp/project/child/views.py
# views.py - child
from flask import Blueprint,render_template,redirect,url_for
from project import db
from project.models import Child
from project.child.forms import AddForm, DelForm

child_blueprint = Blueprint('child', __name__, template_folder='templates/child')

@child_blueprint.route('/add', methods=['GET','POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        new_child = Child(name)
        db.session.add(new_child)
        db.session.commit()
        return redirect(url_for('child.list'))

    return render_template('add_child.html', form=form)


@child_blueprint.route('/list')
def list():
    children = Child.query.all()
    return render_template('list_child.html', children=children)


@child_blueprint.route('/delete', methods=['GET','POST'])
def delete():
    form = DelForm()

    if form.validate_on_submit():
        cid = form.id.data
        remove_child = Child.query.get(cid)
        db.session.delete(remove_child)
        db.session.commit()
        return redirect(url_for('child.list'))

    return render_template('delete_child.html', form=form)

05_LargeFlaskApp/project/father/views.py
# views.py - father
from flask import Blueprint,render_template,redirect,url_for
from project import db
from project.models import Father
from project.father.forms import AddForm

father_blueprint = Blueprint('father', __name__, template_folder='templates/father')

@father_blueprint.route('/add', methods=['GET','POST'])
def add():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        child_id = form.child_id.data
        new_father = Father(name,child_id)
        db.session.add(new_father)
        db.session.commit()
        return redirect(url_for('child.list'))

    return render_template('add_father.html', form=form)

05_LargeFlaskApp/project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

  <head>
    <meta charset="utf-8">
    <title>Flask-App</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{{url_for('index')}}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{{url_for('child.add')}}">Enroll Child</a>
          <a class="nav-item nav-link" href="{{url_for('child.list')}}">List Child</a>
          <a class="nav-item nav-link" href="{{url_for('child.delete')}}">Remove Child</a>
          <a class="nav-item nav-link" href="{{url_for('father.add')}}">Register Father</a>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
  </body>

</html>

05_LargeFlaskApp/project/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
  <br><br>
  <h1>Welcome to Child Adoption Site</h1>
</div>

{% endblock %}